// productData.js
export const products = [
  {
    id: 1,
    name: "Perplexity Labs",
    tagline: "Bring your projects to life faster than ever before",
    tags: ["Productivity", "Artificial Intelligence", "Search"],
    comments: 6,
    upvotes: 444,
    image: "https://ph-files.imgix.net/db193b4c-13cc-4700-8cde-ebac26d3c247.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=64&h=64&fit=crop&frame=1&dpr=1",
  },
  {
    id: 2,
    name: "OpenMemory MCP",
    tagline: "Memory for your AI Tools",
    tags: ["Productivity", "Developer Tools", "Artificial Intelligence"],
    comments: 16,
    upvotes: 340,
    image: "https://ph-files.imgix.net/27196cc9-4bb6-42de-abd8-9b1cdeba7562.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=64&h=64&fit=crop&frame=1&dpr=1",
  },
  {
    id: 3,
    name: "Podgen",
    tagline: "Generate AI Podcasts from prompts, youtube, links and files",
    tags: ["Artificial Intelligence", "Tech", "Audio"],
    comments: 9,
    upvotes: 239,
    image: "https://ph-files.imgix.net/a842fb62-c77e-4466-8206-86bf8780e048.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=64&h=64&fit=crop&frame=1&dpr=1",
  },
  {
    id: 4,
    name: "Manus Slides",
    tagline: "Instant, stunning presentations from a single prompt",
    tags: ["Productivity", "Artificial Intelligence"],
    comments: 13,
    upvotes: 240,
    image: "https://ph-files.imgix.net/3e2fc9f5-44d5-4154-93e8-3c1f02c6e557.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=64&h=64&fit=crop&frame=1&dpr=1",
  },
  {
    id: 5,
    name: "Odyssey",
    tagline: "AI video you can both watch and interact with in real-time",
    tags: ["Artificial Intelligence", "Games", "Video"],
    comments: 18,
    upvotes: 229,
    image: "https://ph-files.imgix.net/23a83410-1663-4926-b712-38967e9bcb41.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=64&h=64&fit=crop&frame=1&dpr=1",
  },
];
